# Server Port
server.port=8081

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:healthhubdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2

#http://localhost:8080/h2/login.jsp?jsessionid=5a4fdb8464fa110449aa5b3e3da13fab